#ifndef CERT_H

#define CERT_H

const char * rootCACertificate = \
//  "-----BEGIN CERTIFICATE-----\n"


"-----BEGIN CERTIFICATE-----\n" 
"MIIDWTCCAkGgAwIBAgIUEiv0GyCditLx/OVrwYboUBVSxnEwDQYJKoZIhvcNAQEL\n" 
"BQAwTTFLMEkGA1UECwxCQW1hem9uIFdlYiBTZXJ2aWNlcyBPPUFtYXpvbi5jb20g\n" 
"SW5jLiBMPVNlYXR0bGUgU1Q9V2FzaGluZ3RvbiBDPVVTMB4XDTIzMDExMzA5NDgz\n" 
"MFoXDTQ5MTIzMTIzNTk1OVowHjEcMBoGA1UEAwwTQVdTIElvVCBDZXJ0aWZpY2F0\n" 
"ZTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMr5ejuOTGU4MTUxnDbX\n" 
"/oIpe/lzaJsC5Ct12BzQjrY4H3U4yoQqJg3a5VVuQvN0xuK3H9Xg4cT4JcQXsJyl\n" 
"Xe8AUQMNoYl8tyQ6U2otCDqbNGohg3rkJh9hpFaUzIAEaI74hD7VlVoxyf0vx6sF\n" 
"Nsy3LKKdkrCEJ0dwu8HQHfpa15ajoira7lzSE3EAJSU8rvFFlwH31TOjT6pIfr10\n" 
"ES2EDE8WE+SsiPXMOK+hhx93MJSBQ4qZmc2es80kKyG5joVMtFrodauNJFlXdpcL\n" 
"fdpEkmL7dmWWa0BcHVfAKxxRLRi2hIqsGAJPZLtxLWfu4W6L7wBP9BCk2iXodZFG\n" 
"WukCAwEAAaNgMF4wHwYDVR0jBBgwFoAU0nOcZaYntBFmDPMjpAoOLeZdR/4wHQYD\n" 
"VR0OBBYEFCG7LZK5lMKShTE3+1pJAqEMOKNjMAwGA1UdEwEB/wQCMAAwDgYDVR0P\n" 
"AQH/BAQDAgeAMA0GCSqGSIb3DQEBCwUAA4IBAQBH5yFlFJQyBVFQAG3cweLHRrlF\n" 
"OgSpO/MPO3JkiHPvUj2zfH/aEwJsO+Ycte/5lPq+eKk5Wto1zj+JrIwWO+JM8RFU\n" 
"GnEQgUFLXlRNNw8xv1COTTD0L7bK4P5q2y2fmZgdTVKtQtl7DYqOifl2zuWHPY8j\n" 
"VGgV/kJU/OFcVLEjwf4HQylFgpkNeguBPN+YAm9KQOsAK7aLfz689EAfP3VnbZFC\n" 
"hhPh7xlRGS5POD0uRF7solOYAzBX9UpJLFMT3rXokdIwYzhG6M5Mj7t4zGqt0YL2\n" 
"5DrPxmuXkINNen8YuzrSdLZST0Sl3d9Z0sweafhyef677LV8xa1tWjUzxytp\n" 
"-----END CERTIFICATE-----\n"; 



/*
"MIIDxTCCAq2gAwIBAgIQAqxcJmoLQJuPC3nyrkYldzANBgkqhkiG9w0BAQUFADBs\n"
"MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3\n"
"d3cuZGlnaWNlcnQuY29tMSswKQYDVQQDEyJEaWdpQ2VydCBIaWdoIEFzc3VyYW5j\n"
"ZSBFViBSb290IENBMB4XDTA2MTExMDAwMDAwMFoXDTMxMTExMDAwMDAwMFowbDEL\n"
"MAkGA1UEBhMCVVMxFTATBgNVBAoTDERpZ2lDZXJ0IEluYzEZMBcGA1UECxMQd3d3\n"
"LmRpZ2ljZXJ0LmNvbTErMCkGA1UEAxMiRGlnaUNlcnQgSGlnaCBBc3N1cmFuY2Ug\n"
"RVYgUm9vdCBDQTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMbM5XPm\n"
"+9S75S0tMqbf5YE/yc0lSbZxKsPVlDRnogocsF9ppkCxxLeyj9CYpKlBWTrT3JTW\n"
"PNt0OKRKzE0lgvdKpVMSOO7zSW1xkX5jtqumX8OkhPhPYlG++MXs2ziS4wblCJEM\n"
"xChBVfvLWokVfnHoNb9Ncgk9vjo4UFt3MRuNs8ckRZqnrG0AFFoEt7oT61EKmEFB\n"
"Ik5lYYeBQVCmeVyJ3hlKV9Uu5l0cUyx+mM0aBhakaHPQNAQTXKFx01p8VdteZOE3\n"
"hzBWBOURtCmAEvF5OYiiAhF8J2a3iLd48soKqDirCmTCv2ZdlYTBoSUeh10aUAsg\n"
"EsxBu24LUTi4S8sCAwEAAaNjMGEwDgYDVR0PAQH/BAQDAgGGMA8GA1UdEwEB/wQF\n"
"MAMBAf8wHQYDVR0OBBYEFLE+w2kD+L9HAdSYJhoIAu9jZCvDMB8GA1UdIwQYMBaA\n"
"FLE+w2kD+L9HAdSYJhoIAu9jZCvDMA0GCSqGSIb3DQEBBQUAA4IBAQAcGgaX3Nec\n"
"nzyIZgYIVyHbIUf4KmeqvxgydkAQV8GK83rZEWWONfqe/EW1ntlMMUu4kehDLI6z\n"
"eM7b41N5cdblIZQB2lWHmiRk9opmzN6cN82oNLFpmyPInngiK3BD41VHMWEZ71jF\n"
"hS9OMPagMRYjyOfiZRYzy78aG6A9+MpeizGLYAiJLQwGXFK3xPkKmNEVX58Svnw2\n"
"Yzi9RKR/5CYrCsSXaQ3pjOLAEFe4yHYSkVXySGnYvCoCWw9E1CAx2/S6cCZdkGCe\n"
"vEsXCS+0yx5DaMkHJ8HSXPfqIbloEpw8nL+e/IBcm2PN7EeqJSdnoDfzAIJ9VNep\n"
"+OkuE6N36B9K\n"
"-----END CERTIFICATE-----\n";
*/
#endif
